### ISSUE TITLE
when this program processed, an error like that occurs "expected initializer before 'PulseProcessor' "

### ISSUE THREAD

**Issue by Arwenlearn** [pi-null-mezon/vpglib#1]
when this program processed, an error like that occurs "expected initializer before 'PulseProcessor' ", I can't solve the error, do you know why?

**Comment by pi-null-mezon** [comment]
When this happens? 
Try this sequence of build steps for MS Win:
0) Create appropriate directory structure:
    FileSystem >> C:/Programming/vpglib - here source code of project should resides
    FileSystem >> C:/Programming/3rdParties/opencv310 - here binaries of opencv v.3.1 should resides 
1) Open project vpglib.pro in Qt_Creator, run qmake and then build project;
2) Open project Test_Device.pro in Qt_Creator (comment CONFIG += designbuild), run qmake and then build project;
3) Start vpglight.exe from Qt_Creator;

**Comment by pi-null-mezon** [comment]
@Arwenlearn have you solved the problem?

**Comment by Arwenlearn** [comment]
Thanks for your help, I have  successfully implemented.  Some time ago, I was busy with  my project, forget to reply, so sorry~

**Comment by TenSir** [comment]
@Arwenlearn  你好， 我也是一名中国的学生，你现在关于这个项目的问题解决了吗？  Github上没有你的联系方式，没办法联系你
