### ISSUE TITLE
Build instructions for linux docker

### ISSUE THREAD

**Issue by maddyonline** [pi-null-mezon/vpglib#10]
Starting with an opencv docker container, what are build instructions for this project? I started with a docker container [janza/docker-python3-opencv](https://github.com/janza/docker-python3-opencv) and installed qt/qmake using `apt-get install g++ qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x`. Then I don't know how to proceed. I tried doing `qmake` inside Shared folder and `make` but it fails with the following error.

```
/usr/bin/ld: cannot find -lvpg
/usr/bin/ld: cannot find -lopencv_face
```

**Comment by pi-null-mezon** [comment]
Of cource you can not link to this libraries (vpg anf opencv_face) by default. First you should build them.

**Comment by maddyonline** [comment]
Thanks for your quick response. Could you recommend the order in which to build various things? In particular, I am not familiar with qmake and `.pri` build files. Is there a command line build script that you can recommend to build this project on an ubuntu linux distro for example?

**Comment by pi-null-mezon** [comment]
First you should build and install opencv on your system. Then, to build vpglib:
```
#!/bin/bash
clone https://github.com/pi-null-mezon/vpglib.git 
cd vpglib/Library
mkdir build && cd build
qmake ../buildvpglib.pro
make
# And optionally to install in /usr/local/lib
make install
sudo ldconfig
```

**Comment by pi-null-mezon** [comment]
Will be closed
