### ISSUE TITLE
Спросите о принципе оценки спектра мощности

### ISSUE THREAD

**Issue by Z-Xiong** [pi-null-mezon/vpglib#11]
https://github.com/pi-null-mezon/vpglib/blob/3179139baac8465f6717f773e5ad0e7111939e10/Library/src/pulseprocessor.cpp#L122

Я не совсем понимаю принцип вашей оценки спектра мощности, на каком методе она основана? Есть ли у вас какие-либо ссылки или документы?

**Comment by pi-null-mezon** [comment]
Power spectrum of a time-domain signal can be evaluated in frequency domain as a square of absolute value of Discrete Fourier Transform divided by observation time. This function makes such calculations. What are particularly you interested in?

**Comment by Z-Xiong** [comment]
Thanks a lot for your answer! I still have the following three questions, I wonder if you can answer them?

https://github.com/pi-null-mezon/vpglib/blob/3179139baac8465f6717f773e5ad0e7111939e10/Library/src/pulseprocessor.cpp#L174
https://github.com/pi-null-mezon/vpglib/blob/3179139baac8465f6717f773e5ad0e7111939e10/Library/src/pulseprocessor.cpp#L187
https://github.com/pi-null-mezon/vpglib/blob/3179139baac8465f6717f773e5ad0e7111939e10/Library/src/pulseprocessor.cpp#L184
Q1：For the estimation of the heart rate value, can it be understood as a weighted average?
Q2：What is the theoretical basis for the calculation of the signal-to-noise ratio? Why multiply the following numbers？
(1.0f / (1.0f + bias*bias))
Q3：The method here should be the periodogram method, right? Have you tried other methods of power spectrum estimation? Such as Blackman-Tukey (BT) method, AR model method, or frequency estimation method based on feature space (such as MUSIC method).

**Comment by pi-null-mezon** [comment]
1: Yes
2: _bias_ here is how far the index of harmonic with maximum power is from the weighted average index. Can not remember if it was found anywhere in literature or just was applied voluntarily
3: Should be for whom or what? No. Fourier was good enough.

**Comment by Z-Xiong** [comment]
Thank you very much for your answer, excellent project.
