### ISSUE TITLE
Could you please kindly send me your reference list of your algorithm?

### ISSUE THREAD

**Issue by Arwenlearn** [pi-null-mezon/vpglib#2]

**Comment by pi-null-mezon** [comment]
Hi, I have started algorithm development after this article - Ming-Zher Poh, Daniel J. McDuff, and Rosalind W. Picard "Non-contact, automated cardiac pulse measurements using video imaging and blind source separation", it was in 2011 year. Then I periodically found another messages about similar techniques but can not say that they add a lot.

**Comment by pi-null-mezon** [comment]
Check this https://github.com/pi-null-mezon/QPULSECAPTURE/wiki
