### ISSUE TITLE
How running this project?

### ISSUE THREAD

**Issue by TenSir** [pi-null-mezon/vpglib#3]
How to bulid the library ? I am confused ,Could you take a screenshot ? Thanks again.

**Comment by pi-null-mezon** [comment]
For what platform we will work? Windows or Linux? Is Opencv binaries have already been installed?

**Comment by TianHao1991** [comment]
The  platform is  windows 10. I have  downloaded  ”opencv-3.1.0.exe” and Unpacked to ”D:\opencv310 ” that is Opencv binaries ? What's next ?  it's very kind of you.

**Comment by TenSir** [comment]
The  platform is  windows 10. I have  downloaded  ”opencv-3.1.0.exe” and Unpacked to ”D:\opencv310 ” that is Opencv binaries ? What's next ?  it's very kind of you.

**Comment by pi-null-mezon** [comment]
Yes it is opencv binaries, but you should also ckeck the compiler version of this binaries. Because we need to build vpglib by compatible compiler version. So, move to "D:\opencv310\bin\..."  and check what version of binaries do you have. Inside this directory you should find "x86" and "x64", and inside subdirectories something like "vc12" (it means MS Visual Studio 2013) or "vc14" (MSVS2015) or "gcc". Check and tell me what you have.

**Comment by TenSir** [comment]
"D:\opencv310\build\bin...‘’only have  two files,they are "opencv_ffmpeg310.dll"and "opencv_ffmpeg310._64dll".   Inside "D:\opencv310\build\x64..."there are "vc12"and "vc14" two files. And no directory of "D:\opencv310\build\x86...".

**Comment by pi-null-mezon** [comment]
Ok, it means that you have installed 64-bit version of the library both for MS Visual studio 2013 and 2015. The next question is: have you installed MS Visual studio 2013 or 2015 on your machine? If not, do it. I suggest to select MSVC2015 Community. You can freely download it from the microsoft website.

**Comment by TenSir** [comment]
I have installed MS Visual studio  2015(installation package about 4GB). What should i  do next ?

**Comment by pi-null-mezon** [comment]
1) Dowload vpglib. Let's suppose that you move it to D:/vpglib
2) Open Qt Creator
3) From the file menu open project file D:/vpglib/Library/buildvpg.pro (chose MSVC2015x64 toolset)
4) From the project tree move to opencv.pri and change version of the library to 310, also adjust all paths for your system
5) Run qmake from the Build menu
6) Run build project from the Build menu (Ctrl+B)

**Comment by TenSir** [comment]
Thanks,I'll try it .By the way,the versions of Qt Creator  i choose "qt-opensource-windows-x86-msvc2015_64-5.8.0.exe” ,right ?

**Comment by pi-null-mezon** [comment]
Depends on your operating system. Is it x86 or x64 bit?

**Comment by TenSir** [comment]
Win10, x64. So,i will be use  "qt-opensource-windows-x86-msvc2015_64-5.8.0.exe" instead of  "qt-opensource-windows-x86-msvc2015-5.8.0.exe" ?

**Comment by pi-null-mezon** [comment]
Yes, let's use 64-bit version.

**Comment by TenSir** [comment]
Unfortunately,I tested as you said, but there is an error: "LINK: fatal error LNK1104: unable to open the file 'vpgd.lib'" ,do you know why ? I made a search  online, but no results.
Excuse me,What version of the operating system you are using, and what version of Qt ?

Thanks a lot!

**Comment by pi-null-mezon** [comment]
I am tested building process on Win7, Win10, Raspbian and Ubuntu16.04. Please attach the view of projects tree when you open buildvpg.pro. Also chek in Qt Creator's options that you have MSVC2015x64 build kit.

**Comment by pi-null-mezon** [comment]
I am tested building process on Win7, Win10, Raspbian and Ubuntu16.04. It seems that you have tried to build not the buildvpg.pro but something else. Please attach the view of project tree when you open buildvpg.pro. Also chek in Qt Creator's options that you have MSVC2015x64 build kit.

**Comment by TenSir** [comment]
Under your guidance, I have successfully completed the project.Thank you very much for your help.
And welcome to visit Fuzhou University (China,Fujian province) at your convenience time.

**Comment by pi-null-mezon** [comment]
Nice to hear that! Thanks for the invitation.

**Comment by stonebb** [comment]
l really want to konw how to do those as you said. but it is hard for me. l really want to konw how to use the  Qt Creator.  
1.Dowload vpglib. Let's suppose that you move it to D:/vpglib
2.Open Qt Creator
3.From the file menu open project file D:/vpglib/Library/buildvpg.pro (chose MSVC2015x64 toolset)
4.From the project tree move to opencv.pri and change version of the library to 310, also adjust all paths  for your system
5.Run qmake from the Build menu
6.Run build project from the Build menu (Ctrl+B)
l have done before 4 step. and l don't know how to do the 5 step and 6 step.
as a green hand, l really need some detail help .thanks a lot.

**Comment by pi-null-mezon** [comment]
@stonebb I am sorry, but your question is not about my project, but about how to work in Qt Creator. I will not respond on this.
