### ISSUE TITLE
Could you tell me what's the version of the Dlib in the project? 

### ISSUE THREAD

**Issue by VanillaHeaven** [pi-null-mezon/vpglib#4]
Excuse me. Could you tell me what's the version of the Dlib in the project? I use DLib-19.0, and try to change the path in the file "dlib.pri“, but there isn't "include" folder in my dlib folder.  Do I need to compile it? Thank you.

**Comment by pi-null-mezon** [comment]
@VanillaHeaven hi. Last time I have just used a last snapshot of the https://github.com/davisking/dlib.git. Also I have manually adjusted dlib's install directory by the CMake utility. You should know however that dlib is used only in new experimental part of the vplib project (vpgtracker), so it is not needed for the rest apps from the vpglib

**Comment by VanillaHeaven** [comment]
Thank you so much! I successfully run the project. I'm a student from China, and I have been trying to run your project in the past few days. Because I'm a beginner in using OpenCV and QT, there were some toubles  when I tried to run the project, but I have solved them now. Thank you for your reply!
