### ISSUE TITLE
compile failure

### ISSUE THREAD

**Issue by paryang** [pi-null-mezon/vpglib#6]
Hi, I am trying to build the project under windows 10 with vs2013, got the 7 "unresolved external symbol" erros. 
ERROR LNK2019: unresolved external symbo vpg::FaceProcessor::__skinColor(****)  which is referenced at vpg::FaceProcessor::enrollImage(***)
same errors for:
1. FaceProcessor::vftable
2. PeakDetector::__loop
3. PeakDetector::__seek
4. PulseProcessor::__loop
5. PulseProcessor::__seek
6. PulseProcessor::vftable

all these symbols are defined in there include file, but no implementation in source files.
BTW, I don't use the buildvpglib.pro to build the vpglib, jusr add source files and include files to the project with opencv headers & libs, then build directly.
What should I do to get these errors solved?

**Comment by paryang** [comment]
@Pi-null-meson

**Comment by pi-null-mezon** [comment]
Did you #define in your project VPG_BUILD_FROM_SOURCE?
